version: '3.4'
services:

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin_ct
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=pedrovh040110@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=ADWVAW231Fawwee131#$2123
    ports:
      - 5050:80
    networks:
      - backend
networks:
  backend:
